apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "0223 Comp"
  description: "0223 Comp"
  annotations:
    github.com/project-slug: 
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "Dinesh Test|DineshKumar_Chandrasekaran@comcast.com"
